### ISSUE TITLE
Question About Feedback Bench

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [kaistAI/prometheus#11]
Hello, very interesting work!

I wonder if you plan to release the feedback bench tested in your paper. I cannot found this part of test set on the huggingface pages.

Thank you so much.

**Comment by SeungoneKim** [comment]
@gmftbyGMFTBY Hello, thank you for your interest in our paper!

You can refer to the 2 JSON files in the following link:
evaluation/benchmark/data

The feedback_collection_test.json and feedback_collection_ood_test.json are the Feedback Bench tested in our paper.
Note that the ood includes 1K instances encompassing 50 score rubrics that were not included in the training process.

Hope this helps!
