### ISSUE TITLE
Demo of Prometheus

### ISSUE THREAD

**Issue by Jiaxu-Zhao** [kaistAI/prometheus#13]
Hi, thanks for sharing this work, it's really helpful. May I know if there's a demo people can use or test the system?

**Comment by SeungoneKim** [comment]
Hey @zhao1402072392 , thanks for your interest in our work!

Unfortunately, we don't have the compute to set up a demo at the moment. But the 7B model would definitely run at Google Colab. Check out the example code and input template at our huggingface README.

https://huggingface.co/kaist-ai/prometheus-13b-v1.0

Let me know if there is any issue!
