### ISSUE TITLE
Prometheus using no reference materials

### ISSUE THREAD

**Issue by maurovitaleBH** [kaistAI/prometheus#14]
Hi everyone, 
very interesting work. However, I'm wondering if I can use prometheus for evaluating some metrics that does not need ground truth (for example the groundedness in a rag system, that is calculated from an answer with respect to some context pieces). How can I do that? For now, I'm just removing reference answer from the prompt

**Comment by SeungoneKim** [comment]
@maurovitaleBH Hello Mauro, thanks for your interest in our work!

Evaluating whether the response is grounded to some additional piece of context could also have a reference answer (one that adheres to the provided context). 

Yet, if you want to scale things up and quickly want to try prometheus, you could just remove the reference answer from the prompt as you mentioned. Yet, it will not guarantee as good performance compared to preparing a reference answer, which is a trade-off!
