### ISSUE TITLE
How to evaluate HHH, MT_Bench_human? Where to get human scores for other val sets?

### ISSUE THREAD

**Issue by deshwalmahesh** [kaistAI/prometheus#19]
**1. Can we say Preference data is an extension of Feedback data? There is a huge difference in numbers.**
(I know I'm making set of strings so not a good indicator but still sticking to my question to confirm whether Old and New rubrics are same or not)

Hi, while testing very vaguely, I found that there is difference in data. Not an issue but just asking why didn't you use the extension of Old data to generate new data `(Answer B)`? Seems like very few rubrics are same.

<img width="852" alt="Screenshot 2024-05-06 at 10 12 34 AM" src="https://github.com/prometheus-eval/prometheus/assets/50293852/4b79b046-440a-4ed6-81cb-fbf088e2bee7">

# ---
Another thing is that, how have you evaluate the `HHH` data? It is `tie:0/1`. Can you please explain your criteria? Similarly the `mt_human` data is `selected/rejected` answer.

Apart from `Flask`, there is no human scores but just `GPT-4`. How can we get human scores as well? Are the scores joined on Mean/ Median/ Top / Min / Max etc?

@scottsuk0306  @SeungoneKim  @eltociear

**Comment by juyoungml** [comment]
Closing this - already resolved in `prometheus-eval` repo!
