### ISSUE TITLE
A functional command example for model training (also on a single GPU)?

### ISSUE THREAD

**Issue by mqo00** [kaistAI/prometheus#7]
Hi, I have limited experience fine-tuning llama models and haven't used [llama-recipes](https://github.com/facebookresearch/llama-recipes/tree/main) before. I've been trying to recreate the experiment but I don't really know what should be the argument for the example torchrun command in the [readme](https://github.com/kaistAI/prometheus/blob/main/README.md). **Can you provide the exact command you used to fine-tune e.g., llama2-7b-chat?** 

For example, what should be the --dataset (your [train.py](https://github.com/kaistAI/prometheus/blob/main/train/configs/training.py) says "feedback_collection_freeform_dataset" while [dataset.py](https://github.com/kaistAI/prometheus/blob/main/train/configs/datasets.py) only has "feedback_collection_dataset")?
And --data_file seems to be a weird variable that doesn't really get used, you have this [sample_train_data.json](https://github.com/kaistAI/prometheus/blob/main/train/sample_train_data.json) file, but if you load your HF kaist-ai/Feedback-Collection dataset, do you just pass it in --dataset? 

Also, I'm trying to fine-tune with a single GPU (e.g., an A10G on aws ec2 g5-x2large instance), I'm half-guessing the arguments, following the suggestions of llama-receipes on [fine-tuning with 1 GPU](https://github.com/facebookresearch/llama-recipes/blob/main/docs/single_gpu.md), and I run the command below in the train directory, which took about 1.5 hrs.

**Do you have any suggestions for adjusting the code when running on a single GPU?** Especially hyperparameter-wise, any experiments you've done? If it's a single GPU I guess I don't need fsdp and should use peft? Did lora/qlora decrease your model performance, it doesn't seem like you used it? Batch size, gradient_accumulation_steps, use_fast_kernels, etc? I want to further fine-tune the Prometheus 7b model on a subset of 10k of your training data to see if it brings any differences.
Any insight will be appreciated! 
```
python -m llama_finetuning 
  --use_peft 
  --peft_method lora 
  --quantization 
  --model_name "meta-llama/Llama-2-7b-chat-hf" 
  --hf_cache_dir "hf_cache_dir"  
  --batch_size_training 1 
  --dist_checkpoint_root_folder "model_checkpointing" 
  --dist_checkpoint_folder "model_checkpointing" 
  --dataset "feedback_collection_dataset" 
  --data_file sample_train_data.json 
  --num_epochs 1 
  --scheduler "step"
```

Also, in your training script, wandb doesn't seem to be logging any loss or lr besides GPU usage by time, the resulting loss all have a nan value, and the code ended with a 
```
Exception in thread NetStatThr
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
...
    sent = self._sock.send(data)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
BrokenPipeError: [Errno 32] Broken pipe 
```
And the wandb log is as follows:
```
 1 Loading checkpoint shards: 100%|███████████████████| 2/2 [01:16<00:00, 38.04s/it]
 2 /opt/conda/lib/python3.10/site-packages/peft/utils/other.py:135: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
 3   warnings.warn(
 4 /opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py:329: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
 5   warnings.warn(
 6 Training Epoch0:   0%|                                                                    | 0/1036 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
 7   warnings.warn(
 8 /opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:322: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
 9   warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
10 --> Model meta-llama/Llama-2-7b-chat-hf
11 --> meta-llama/Llama-2-7b-chat-hf has 262.41024 Million params
12 trainable params: 8,388,608 || all params: 6,746,804,224 || trainable%: 0.12433454005023165
13 --> Training Set Length = 1036
14 Training Epoch0: 100%|███████████████████████████████████████████████████████| 1036/1036 [1:26:22<00:00,  5.00s/it]
15 Max CUDA memory allocated was 10 GB
16 Max CUDA memory reserved was 12 GB
17 Peak active CUDA memory was 10 GB
18 Cuda Malloc retires : 0
19 CPU Total Peak Memory consumed during the train (max): 1 GB
20 we are about to save the PEFT modules
21 PEFT modules are saved in PATH/to/save/PEFT/model directory
22 Epoch 1: train_perplexity=nan, train_epoch_loss=nan, epcoh time 5182.987906961s
23 Key: avg_train_prep, Value: nan
24 Key: avg_train_loss, Value: nan
25 Key: avg_epoch_time, Value: 5182.987906961
26 Key: avg_checkpoint_time, Value: 0.09371346700027061
```
Thanks!

**Comment by agokrani** [comment]
Hi @mqo00,

Did you find the solution to your problem. I also want to finetune this model more on custom datasets. Wouldn't it be better to do this via huggingface SFTTrainer? 

@SeungoneKim your help on this would be greatly appreciated.

**Comment by SeungoneKim** [comment]
@mqo00 Hello, thank you for your interest in our paper & sorry for the late response!

I think the problem might be due to this line 80 & 93:
https://github.com/kaistAI/prometheus/blob/60e2c58956d670532d48ae94fefe278809b98aee/train/llama_finetuning.py#L80C1-L80C1

Please fix the entity to your wandb account:)

**Comment by mqo00** [comment]
Hi @agokrani, sorry I wanted to reply earlier. Yes I eventually figured out the solution, I changed the code a bit since the [llama-recipes](https://github.com/facebookresearch/llama-recipes) has some updates such as [this](https://github.com/facebookresearch/llama-recipes/pull/280), and I also added some more customized commands with wandb logs. In the end, if you want to fit everything in one GPU I needed to use PEFT+8bit quantization.
Just attaching some bash script I run for reference, I just replaced the `sample_train_data.json` with my dataset

this one uses PEFT

```
 #!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=50G
#SBATCH --time=4:00:00
#SBATCH --gres=gpu:A6000:1

python -m llama_finetuning \
 --use_peft \
 --peft_method lora \
 --quantization \
 --model_name "meta-llama/Llama-2-7b-chat-hf" \
 --batch_size_training 8 \
 --gradient_accumulation_steps 4 \
 --dataset "feedback_collection_dataset" \
 --data_file sample_train_data.json \ 
 --num_epochs 1 \
 --scheduler "step" \
 --output_dir "ckpt/peft-llama7b-8x4" 
```

this one uses FSDP
```
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=64G
#SBATCH --time=2:00:00
#SBATCH --gres=gpu:A6000:2

torchrun --nnodes 1 \
    --nproc_per_node 2 \
    llama_finetuning.py \
    --model_name "kaist-ai/prometheus-7b-v1.0" \
    --batch_size_training 4  \
    --gradient_accumulation_steps 7 \
    --dist_checkpoint_root_folder "ckpt" \
    --dist_checkpoint_folder "fsdp" \
    --dataset feedback_collection_dataset \
    --data_file sample_train_data.json \
    --num_epochs 2 \
    --scheduler "step"  \
    --use_fast_kernel \
    --enable_fsdp \
    --pure_bf16 \
    --low_cpu_fsdp
```
